Repository AlexTelon/FlexiCharge-Android, pull requests merged in 2023-09, with the labels that each got.

#155 Feature/register user account
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/com/flexicharge/bolt/UserRegisterTest.kt
  app/src/main/java/com/flexicharge/bolt/activities/ConfirmEmailActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/ForgotPasswordActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/LoginActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/RegisterActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/VerifyActivity.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiInterface.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiJsonResponse.kt
  app/src/main/java/com/flexicharge/bolt/helpers/Constant.kt
  app/src/main/java/com/flexicharge/bolt/helpers/Validator.kt
  app/src/main/res/layout/activity_register.xml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement, account

#158 Hotfix/improve registration flow
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetDropDown.xml
  app/build.gradle
  app/src/androidTest/java/com/flexicharge/bolt/TestApi.kt
  app/src/androidTest/java/com/flexicharge/bolt/TestMainActivity.kt
  app/src/debug/res/values/google_maps_api.xml
  app/src/main/java/com/flexicharge/bolt/activities/LoginActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/RegisterActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/VerifyActivity.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiInterface.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiJsonResponse.kt
  app/src/main/res/layout/activity_register.xml
  app/src/main/res/layout/activity_verify_email.xml
  app/src/test/java/com/flexicharge/bolt/ExampleUnitTest.kt
  build.gradle
Labels: account, change, hotfix

#160 Documentation/updated the readme documentation
  README.md
Labels: documentation

#181 Maintenance/upgrade Gradle version
  .idea/deploymentTargetDropDown.xml
  README.md
  app/build.gradle
  app/src/androidTest/java/com/flexicharge/bolt/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/flexicharge/bolt/TestApi.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/flexicharge/bolt/activities/AboutActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/ConfirmEmailActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/ForgotPasswordActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/KlarnaActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/KlarnaOrderCompletedActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/LoginActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/MainActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/ProfileMenuLoggedInActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/ProfileMenuLoggedOutActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/QrActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/RegisterActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/SplashscreenActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/VerifyActivity.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/EntryManager.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/RemoteChargePoints.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/RemoteCharger.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/RemoteChargers.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/RemoteObject.kt
  app/src/main/java/com/flexicharge/bolt/activities/businessLogic/RemoteTransaction.kt
  app/src/main/java/com/flexicharge/bolt/adapters/ChargePointListAdapter.kt
  app/src/main/java/com/flexicharge/bolt/adapters/ChargersListAdapter.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiInterface.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/ApiJsonResponse.kt
  app/src/main/java/com/flexicharge/bolt/api/flexicharge/WebSocketJsonMessage.kt
  app/src/main/java/com/flexicharge/bolt/api/klarna/OrderClient.kt
  app/src/main/java/com/flexicharge/bolt/helpers/MapHelper.kt
  app/src/main/res/layout/activity_about.xml
  app/src/main/res/layout/activity_charging_history.xml
  app/src/main/res/layout/activity_klarna.xml
  app/src/main/res/layout/activity_verify_email.xml
  app/src/main/res/layout/chargepoint_list_item.xml
  app/src/main/res/layout/charger_list_item.xml
  app/src/test/java/com/flexicharge/bolt/ExampleUnitTest.kt
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: quality, maintenance
